<?php if($this->canShowBlock()): ?>
<h2 class="h2 product-detail"><?php echo $this->getLayer()->getCurrentCategory()->getName() ?></h2>
<div class="categorylink">Orthopaedic Models</div>
<h3 class="narrowby">Narrow By:</h3>
    <div class="categorywrap">
        <?php echo $this->getStateHtml() ?>
        <?php if ($this->getLayer()->getState()->getFilters()): ?>
            <div class="actions"><a href="<?php echo $this->getClearUrl() ?>"><?php echo $this->__('Clear All') ?></a></div>
        <?php endif; ?>
        <?php if($this->canShowOptions()): ?>
            
                <?php $_filters = $this->getFilters() ?>
                <?php foreach ($_filters as $_filter): ?>
                <?php if($_filter->getItemsCount()): ?>
                    <div class="categoryblock w-clearfix" data-name="<?php echo $this->__($_filter->getName()) ?>"><a class="skip-link" data-target-element="#<?php echo $this->__($_filter->getName()) ?>"><h4 class="categoryblocktext"><?php echo $this->__($_filter->getName()) ?></h4><h4 class="categoryblocktext farrow"></h4></a></div>

                    <dd id="<?php echo $this->__($_filter->getName()) ?>" class="skip-content"  ><?php echo $_filter->getHtml() ?></dd>
                <?php endif; ?>
                <?php endforeach; ?>
            <script type="text/javascript">decorateDataList('narrow-by-list')</script>
       <?php endif; ?>
    </div>
<?php endif; ?>







