<?php $_productCollection=$this->getLoadedProductCollection(); $_helper = $this->helper('catalog/output'); if(!$_productCollection->count()): ?>
<p class="note-msg">
    <?php echo $this->__('There are no products matching the selection.') ?></p>
<?php else: 
echo $this->getToolbarHtml();  
if($this->getMode()!='grid'):
    $_iterator=0 ; ?>
<div class="listing-wrap">
    <?php foreach ($_productCollection as $_product): ?>
    <div class="listingrow w-row">

        <div class="listingcol1 w-col w-col-2 w-col-stack">
            <?php $_imgSize=300; ?>
            <a style="color: black;" href="<?php echo $_product->getProductUrl() ?>"?><img style="height: auto; max-height: 100%;" id="product-collection-image-<?php echo $_product->getId(); ?>" src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->keepFrame(false)->resize($_imgSize); ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" /></a>
        </div>
        <div class="listingcol2 w-col w-col-5 w-col-stack">
            <div class="listingcol2paddingdiv">
                <div class="itemdetinfotext listinginfo">
                    <a style="color: black;" href="<?php echo $_product->getProductUrl() ?>"?><?php echo $_helper->productAttribute($_product, $_product->getName() , 'name'); ?></a>
                    <br><span class="itemdetbigandbold"><?php echo ($currency_symbol = Mage::app()->getLocale()->currency( $currency_code )->getSymbol()); echo number_format($_product->getPrice(), 2, '.', '') ?></span>&nbsp; &nbsp;EA &nbsp; &nbsp; Lead Time: <span class="itemdetbold">14 days</span>
                </div>
                <div class="addtocartwrap listing">
                    <?php if(!$_product->canConfigure() && $_product->isSaleable()){ ?>
                    <div class="quantitytext">Quantity:</div>
                    <div class="addtocart_box">
                        <div class="quantityform">
                            <div class="quantitynumber">
                                <?php if(!$_product->isGrouped()): ?>
                                <input style="width: 100%; border: none;" type="text" name="qty" id="qty" placeholder="1" maxlength="12" value="<?php echo $_product->getProductDefaultQty() * 1 ?>" title="<?php echo $this->__('Qty') ?>" class="input-text qty input-quantity" />
                                <?php endif; ?>
                            </div>
                        </div>
                        <?php if(!$_product->canConfigure() && $_product->isSaleable()): ?>
                        <div class="addtocartbutton" style="margin-left: 12px; cursor: pointer" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')">
                            <div class="addtocarttext">Add to Cart</div>
                        </div>
                    </div>
                    <?php elseif($_product->getStockItem() && $_product->getStockItem()->getIsInStock()): ?>
                    <a style="color: white;" title="<?php echo $this->quoteEscape($this->__('View Details')) ?>" href="<?php echo $_product->getProductUrl() ?>">
                        <?php echo $this->__('View Details') ?></a>
                    <?php else: 
                    echo $this->__('Out of stock');  
                    endif; ?>
                    <div class="addtomylists">
                        <?php if ($this->helper('wishlist')->isAllow()) : ?>
                        <a href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>">
                            <?php echo $this->__('Add to Wishlist') ?></a>
                        <?php endif; ?>
                    </div>
                    <?php }else{ ?>
                    <div style="padding-top: 35px;">
                        <p style="float: left; center;color: red; line-height: 50px; font-weight: bold;">Out of stock</p>
                        <div class="addtocartbutton" style="float: right; margin-bottom: 15px;">
                            <a style="color: white;" title="<?php echo $this->quoteEscape($this->__('View Details')) ?>" href="<?php echo $_product->getProductUrl() ?>">
                                <div class="addtocarttext">
                                    <?php if($_product->getStockItem() && $_product->getStockItem()->getIsInStock()){ echo $this->__('View Details'); } ?></div>
                            </a>
                        </div>
                        <div class="addtomylists" style="clear: both">
                            <?php if ($this->helper('wishlist')->isAllow()) : ?>
                            <a href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>">
                                <?php echo $this->__('Add to Wishlist') ?></a>
                            <?php endif; ?>
                        </div>
                    </div>
                    <?php } ?>
                </div>
            </div>
        </div>



        <div class="listingcol3 w-col w-col-5 w-col-stack">
            <div class="height itemdetinfotext listinginfo">Model Type:&nbsp;...
                <br>AnatomyMaterial:&nbsp;.....
                <br>Size:&nbsp;<?php //size
            if($_product->isConfigurable()) {
                $_helper2 = Mage::getModel('catalog/product_type_configurable')
                            ->setProduct($_product);
                $_subproducts = $_helper2
                                ->getUsedProductCollection()
                                ->addAttributeToSelect('size')
                                ->addFilterByRequiredOptions(); 

                $_colors = array();
                $_color_id = array();
                foreach ($_subproducts as $_subproduct) {
                  $label = $_subproduct->getAttributeText('size');
                  $_colors[] = $label;

                  if (!isset($_color_id[$label])) {
                    $_color_id[$label] = $_subproduct->getData('size');
                  }
                }
                $_color_swatch = array_unique($_colors);
                $len = count($array);
                foreach($_color_swatch as $_inner_option_id){
                            echo  " /".$_inner_option_id;
                }

            }

            ?>



                <br>Color:&nbsp; <?php // color
            if($_product->isConfigurable()) {
                $_helper2 = Mage::getModel('catalog/product_type_configurable')
                            ->setProduct($_product);
                $_subproducts = $_helper2
                                ->getUsedProductCollection()
                                ->addAttributeToSelect('color')
                                ->addFilterByRequiredOptions(); 

                $_colors = array();
                $_color_id = array();
                foreach ($_subproducts as $_subproduct) {
                  $label = $_subproduct->getAttributeText('color');
                  $_colors[] = $label;

                  if (!isset($_color_id[$label])) {
                    $_color_id[$label] = $_subproduct->getData('color');
                  }
                }
                $_color_swatch = array_unique($_colors);
                $len = count($array);
                foreach($_color_swatch as $_inner_option_id){
                            echo  " /".$_inner_option_id;
                }

            }

            ?>
                <br>Orientation:&nbsp;...
                <br>
                <br><span class="itemdetailtextsmall">
            <?php echo substr($_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description'),0,110); ?>
                        <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_productNameStripped ?>" class="link-learn"><?php echo $this->__('Learn More') ?></a>
        </span>
            </div>
        </div>
    </div>
    <?php endforeach; ?>
</div>
<script type="text/javascript">
    decorateList('products-list', 'none-recursive')
</script>
<?php else: 
$_collectionSize=$_productCollection->count(); 
$_columnCount=$this->getColumnCount(); ?>
<ul class="products-grid products-grid--max-<?php echo $_columnCount; ?>-col">
    <?php $i=0; foreach ($_productCollection as $_product): ?>
    <li class="item<?php if(($i-1)%$_columnCount==0): ?> first<?php elseif($i%$_columnCount==0): ?> last<?php endif; ?>">
        <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image">
            <?php $_imgSize=210; ?>
            <img id="product-collection-image-<?php echo $_product->getId(); ?>" src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize($_imgSize); ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" />
        </a>
        <div class="product-info">
            <h2 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></a></h2>
            <?php echo $this->getPriceHtml($_product, true);
            if($_product->getRatingSummary()):
                echo $this->getReviewsSummaryHtml($_product, 'short');
            endif; ?>
            <div class="actions">
                <?php if(!$_product->canConfigure() && $_product->isSaleable()): ?>
                <button type="button" title="<?php echo $this->quoteEscape($this->__('Add to Cart')) ?>" class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span><span><?php echo $this->__('Add to Cart') ?></span></span>
                </button>
                <?php elseif($_product->getStockItem() && $_product->getStockItem()->getIsInStock()): ?>
                <a title="<?php echo $this->quoteEscape($this->__('View Details')) ?>" class="button" href="<?php echo $_product->getProductUrl() ?>">
                    <?php echo $this->__('View Details') ?></a>
                <?php else: ?>
                <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span>
                </p>
                <?php endif; ?>
                <ul class="add-to-links">
                    <?php if ($this->helper('wishlist')->isAllow()) : ?>
                    <li>
                        <a href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>" class="link-wishlist">
                            <?php echo $this->__('Add to Wishlist') ?></a>
                    </li>
                    <?php endif; 
                    if($_compareUrl=$this->getAddToCompareUrl($_product)): ?>
                    <li><span class="separator">|</span>
                        <a href="<?php echo $_compareUrl ?>" class="link-compare">
                            <?php echo $this->__('Add to Compare') ?></a>
                    </li>
                    <?php endif; ?>
                </ul>
            </div>
        </div>
    </li>
    <?php endforeach ?>
</ul>
<script type="text/javascript">
    decorateGeneric($$('ul.products-grid'), ['odd', 'even', 'first', 'last'])
</script>
<?php endif; ?>

<?php endif; ?>