<?php if($this->getCollection()->getSize()): ?>
    <?php $_currUrl=($this->getCurrentPage()==1)?
    $this->getPagerUrl(array($this->getOrderVarName()=>$order,  $this->getDirectionVarName()=>$direction,$this->getPageVarName()=>null )):
    $this->getPagerUrl(array($this->getOrderVarName()=>$order,  $this->getDirectionVarName()=>$direction,$this->getPageVarName()=>null ));
    ?>
<div class="filterbar w-row">

    <?php if( $this->isExpanded() ): ?>
        <div class=" filterbarcol1 w-col w-col-3 w-col-stack">
            <div class="view-mode sortby"><?php echo $this->__('Sort by:') ?></div>
            <select style="height: 30px" class="sortbydrop w-clearfix" onchange="setLocation(this.value)" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Sort By')) ?>">
                <?php foreach($this->getAvailableOrders() as $_key=>$_order): ?>
                    <option class="left pagenumlisting" value="<?php echo $this->getOrderUrl($_key, 'asc') ?>"<?php if($this->isOrderCurrent($_key)): ?> selected="selected"<?php endif; ?>>
                        <?php echo $this->__($_order) ?>
                    </option>
                <?php endforeach; ?>
            </select>
        </div>
        <div class="sorter filterbarcol1 w-col w-col-3 w-col-stack">

            <?php if( $this->isEnabledViewSwitcher() ): ?>
                <p class="view-mode">
                    <?php $_modes = $this->getModes(); ?>
                    <?php if($_modes && count($_modes)>1): ?>
                        <label style="display: block; margin-top: 5px;"><?php echo $this->__('View as') ?></label>
                        <?php foreach ($this->getModes() as $_code=>$_label): ?>
                            <?php if($this->isModeActive($_code)): ?>
                                <strong title="<?php echo $_label ?>" class="<?php echo strtolower($_code); ?>"><?php echo $_label ?></strong>
                            <?php else: ?>
                                <a href="<?php echo $this->getModeUrl($_code) ?>" title="<?php echo $_label ?>" class="<?php echo strtolower($_code); ?>"><?php echo $_label ?></a>
                            <?php endif; ?>
                        <?php endforeach; ?>
                    <?php endif; ?>
                </p>
            <?php endif; ?>


         
        </div>
    <?php endif; ?>
    <div class="pager filterbarcol2 w-clearfix w-col w-col-9 w-col-stack">
        <div class="count-container">
            <div class="limiter">
                <label><?php echo $this->__('Per Page') ?></label>
                <select class="perpagedrop" onchange="setLocation(this.value)" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Results per page')); ?>">
                <?php foreach ($this->getAvailableLimit() as  $_key=>$_limit): ?>
                    <option value="<?php echo $this->getLimitUrl($_key) ?>"<?php if($this->isLimitCurrent($_key)): ?> selected="selected"<?php endif ?>>
                        <?php echo $_limit ?>
                    </option>
                <?php endforeach; ?>
                </select>
            </div>
           
            <!-- <div class="pagenumber perpagebox"><div class="pagenumlisting"><?php echo $this->getCurrentPage()?></div></div>
            <div class="pagefloat sortby"> of <?php echo $this->getLastPageNum()?> <a href="<?php echo $_currUrl.'?p=2';?>"></a></div> -->
            <?php echo $this->getPagerHtml() ?>
            <div class="pagefloat sortby"> of <?php echo $this->getLastPageNum()?></div>
            <p class="amount amount--no-pages sortingbaritemnumbers">
                <strong><?php echo $this->__('%s items', $this->getTotalNum()) ?></strong>
            </p>


            
        </div>

        

    </div>
</div>
<?php endif ?>
