

<?php if($this->getCollection()->getSize()): ?>
<div class="filterbar w-row">

    <?php if( $this->isExpanded() ): ?>
        <div class=" filterbarcol1 w-col w-col-3 w-col-stack">
            <div class="view-mode sortby"><?php echo $this->__('Sort by:') ?></div>
            <select style="height: 30px" class="sortbydrop w-clearfix" onchange="setLocation(this.value)" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Sort By')) ?>">
                <?php foreach($this->getAvailableOrders() as $_key=>$_order): ?>
                    <option class="left pagenumlisting" value="<?php echo $this->getOrderUrl($_key, 'asc') ?>"<?php if($this->isOrderCurrent($_key)): ?> selected="selected"<?php endif; ?>>
                        <?php echo $this->__($_order) ?>
                    </option>
                <?php endforeach; ?>
            </select>
        </div>
        <div class="sorter filterbarcol1 w-col w-col-3 w-col-stack">

            <?php if( $this->isEnabledViewSwitcher() ): ?>
                <p class="view-mode">
                    <?php $_modes = $this->getModes(); ?>
                    <?php if($_modes && count($_modes)>1): ?>
                        <label style="display: block; margin-top: 5px;"><?php echo $this->__('View as') ?></label>
                        <?php foreach ($this->getModes() as $_code=>$_label): ?>
                            <?php if($this->isModeActive($_code)): ?>
                                <strong title="<?php echo $_label ?>" class="<?php echo strtolower($_code); ?>"><?php echo $_label ?></strong>
                            <?php else: ?>
                                <a href="<?php echo $this->getModeUrl($_code) ?>" title="<?php echo $_label ?>" class="<?php echo strtolower($_code); ?>"><?php echo $_label ?></a>
                            <?php endif; ?>
                        <?php endforeach; ?>
                    <?php endif; ?>
                </p>
            <?php endif; ?>


         
        </div>
    <?php endif; ?>
    <div class="pager">
        <div class="count-container">
            <?php if($this->getLastPageNum()>1): ?>
                <p class="amount amount--has-pages">
                    <?php echo $this->__('%s-%s of %s', $this->getFirstNum(), $this->getLastNum(), $this->getTotalNum()) ?>
                </p>
            <?php else: ?>
                <p class="amount amount--no-pages">
                    <strong><?php echo $this->__('%s Item(s)', $this->getTotalNum()) ?></strong>
                </p>
            <?php endif; ?>

            <div class="limiter">
                <label><?php echo $this->__('Show') ?></label>
                <select onchange="setLocation(this.value)" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Results per page')); ?>">
                <?php foreach ($this->getAvailableLimit() as  $_key=>$_limit): ?>
                    <option value="<?php echo $this->getLimitUrl($_key) ?>"<?php if($this->isLimitCurrent($_key)): ?> selected="selected"<?php endif ?>>
                        <?php echo $_limit ?>
                    </option>
                <?php endforeach; ?>
                </select>
            </div>
        </div>

        <?php echo $this->getPagerHtml() ?>

    </div>
</div>
<?php endif ?>
