<!DOCTYPE html>
<!-- This site was created in Webflow. http://www.webflow.com-->
<!-- Last Published: Thu Sep 29 2016 20:09:01 GMT+0000 (UTC) -->
<html data-wf-domain="sawbones-product-homepage.webflow.io" data-wf-page="57b55b0ec24ee74912dfc68e" data-wf-site="57994ac141136a134b02557d" data-wf-status="1">

<head>
    <?php echo $this->getChildHtml('head') ?>
    <link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Lato:100,100italic,300,300italic,400,400italic,700,700italic,900,900italic">
    <style type="text/css">
        html {
            -webkit-font-smoothing: antialiased;
            -moz-osx-font-smoothing: grayscale;
            text-shadow: 1px 1px 1px rgba(0,0,0,.004);
        }
    </style>
</head>

<body class="body">
    <?php echo $this->getChildHtml('header') ?>
    <div class="section1 section1proddetail">
       <?php echo $this->getChildHtml('breadcrumbs') ?>
        <div class="w-row">
            <div class="w-col w-col-3">
                <h3 class="narrowby">Narrow By:</h3>
                <div class="categorywrap">
                <?php 
                $parentCategoryId =  Mage::registry('current_category')->getId();
                $cat = Mage::getModel('catalog/category')->load($parentCategoryId);
                $subcats = $cat->getChildren();

                foreach(explode(',',$subcats) as $subCatid){ 
                    $_category = Mage::getModel('catalog/category')->load($subCatid);
                if($_category->getIsActive()) { ?>
                    <div class="categoryblock">
                        <a href="<?php echo $_category->getURL(); ?>"><h4 style="color: black;" class="categoryblocktext">
                        <?php echo $_category->getName(); ?></h4></a>
                        <h4 class="categoryblocktext farrow"></h4>
                    </div>
                <?php }} ?>
                </div>
            </div>
            <div class="categorypagecol2 w-col w-col-9">
                <h2 class="h2 prod-category"><?php $_category_detail=Mage::registry('current_category');
            echo $_category_detail->getName();?></h2>
                <p class="categorypagedesc"><?php echo Mage::getModel('catalog/layer')->getCurrentCategory()->getDescription();  ?>
                </p>
                <?php $parentCategoryId =  Mage::registry('current_category')->getId();
                $cat = Mage::getModel('catalog/category')->load($parentCategoryId);
                $subcats = $cat->getChildren();
                $subcatsleng = strlen($subcats) ;
                if($subcatsleng >0){ ?>
                    <div class="categorypageslider smallslider w-slider" data-animation="slide" data-duration="500" data-infinite="1">
                <div class="w-clearfix w-slider-mask">
                <?php 
                
                    foreach(explode(',',$subcats) as $subCatid){ 
                    $_category = Mage::getModel('catalog/category')->load($subCatid);
                   
                if($_category->getIsActive()) { ?>
                    <div class="categorypageslide w-slide" style="transform: translateX(0px); opacity: 1;">
                        <a href="<?php echo $_category->getURL(); ?>"><div class="categorypageslidepic"></div></a>
                        <div class="categorypageslidetitle">
                            <a href="<?php echo $_category->getURL(); ?>"><h4 class="categorypageslidetitletext"><?php echo $_category->getName(); ?></h4></a>
                        </div>
                    </div>

                <?php }} ?>
                </div>
                    <div class="w-slider-arrow-left">
                        <div class="prodslideicon w-icon-slider-left"></div>
                    </div>
                    <div class="w-slider-arrow-right">
                        <div class="prodslideicon w-icon-slider-right"></div>
                    </div>
                </div>
                <?php }
                ?>
                
                    
                
            </div>
        </div>
    </div>
</body>

</html>