<!DOCTYPE html>
<!-- This site was created in Webflow. http://www.webflow.com-->
<!-- Last Published: Thu Sep 29 2016 20:09:01 GMT+0000 (UTC) -->
<html data-wf-domain="sawbones-product-homepage.webflow.io" data-wf-page="57b55b0ec24ee74912dfc68e" data-wf-site="57994ac141136a134b02557d" data-wf-status="1">

<head>
    <meta charset="utf-8">
    <title>Product Category Page</title>
    <meta content="Product Category Page" property="og:title">
    <meta content="width=device-width, initial-scale=1" name="viewport">
    <meta content="Webflow" name="generator">
    <link href="https://daks2k3a4ib2z.cloudfront.net/57994ac141136a134b02557d/css/sawbones-product-homepage.webflow.e3b042877.css" rel="stylesheet" type="text/css">
    <script src="https://ajax.googleapis.com/ajax/libs/webfont/1.4.7/webfont.js"></script>
    <script type="text/javascript">
        WebFont.load({
            google: {
                families: ["Lato:100,100italic,300,300italic,400,400italic,700,700italic,900,900italic"]
            }
        });
    </script>
    <script src="https://daks2k3a4ib2z.cloudfront.net/0globals/modernizr-2.7.1.js" type="text/javascript"></script>
    <link href="https://daks2k3a4ib2z.cloudfront.net/img/favicon.ico" rel="shortcut icon" type="image/x-icon">
    <link href="https://daks2k3a4ib2z.cloudfront.net/img/webclip.png" rel="apple-touch-icon">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, shrink-to-fit=no" />
    <meta name="HandheldFriendly" content="true" />
    <style type="text/css">
        html {
            -webkit-font-smoothing: antialiased;
            -moz-osx-font-smoothing: grayscale;
            text-shadow: 1px 1px 1px rgba(0, 0, 0, .004);
        }
    </style>
</head>

<body class="body">
    <div class="section-header">
        <div class="navbar w-nav" data-animation="default" data-collapse="medium" data-contain="1" data-duration="400">
            <div class="nav-container w-container">
                <a class="brandwrap w-clearfix w-nav-brand" href="#"><img class="sawboneslogo" src="http://uploads.webflow.com/57994ac141136a134b02557d/57a600cec3e841c509ebf7a2_sawbones-logo-white.png" width="215">
                </a>
                <nav class="nav-menu w-nav-menu" role="navigation"><a class="active nav-link w-nav-link" href="#">Products&nbsp;<span class="fa-blue"></span></a><a class="nav-link w-nav-link" href="#">Materials &amp; Use Guide&nbsp;<span class="fa-blue"></span></a><a class="nav-link w-nav-link" href="#">Custom Models&nbsp;<span class="fa-blue"></span></a>
                </nav>
                <div class="menubutton w-nav-button">
                    <div class="icon w-icon-nav-menu"></div>
                </div>
            </div>
            <div class="search">
                <h3 class="searchicon"></h3>
            </div>
        </div>
    </div>
    <div class="section1 section1proddetail">
       <?php echo $this->getChildHtml('breadcrumbs') ?>







        <div class="cartcheckoutwrap w-clearfix">
            <div class="checkoutwrap">
                <h4 class="checktext">Checkout</h4>
            </div>
            <div class="cartwrap">
                <h1 class="carttext">0<span class="fa checkout"></span></h1>
            </div>
        </div>
        <div class="w-row">
            <div class="w-col w-col-3">
                <h3 class="narrowby">Narrow By:</h3>
                <div class="categorywrap">
                <?php 
                $parentCategoryId =  Mage::registry('current_category')->getId();
                $cat = Mage::getModel('catalog/category')->load($parentCategoryId);
                $subcats = $cat->getChildren();

                foreach(explode(',',$subcats) as $subCatid){ 
                    $_category = Mage::getModel('catalog/category')->load($subCatid);
                if($_category->getIsActive()) { ?>
                    <div class="categoryblock">
                        <a href="<?php echo $_category->getURL(); ?>"><h4 style="color: black;" class="categoryblocktext">
                        <?php echo $_category->getName(); ?></h4></a>
                        <h4 class="categoryblocktext farrow"></h4>
                    </div>
                <?php }} ?>
                </div>
            </div>
            <div class="categorypagecol2 w-col w-col-9">
                <h2 class="h2 prod-category"><?php $_category_detail=Mage::registry('current_category');
            echo $_category_detail->getName();?></h2>
                <p class="categorypagedesc"><?php echo Mage::getModel('catalog/layer')->getCurrentCategory()->getDescription();  ?>
                </p>
                <div class="categorypageslider smallslider w-slider" data-animation="slide" data-duration="500" data-infinite="1">
                    
                <div class="w-clearfix w-slider-mask">
                <?php $parentCategoryId =  Mage::registry('current_category')->getId();
                $cat = Mage::getModel('catalog/category')->load($parentCategoryId);
                $subcats = $cat->getChildren();

                foreach(explode(',',$subcats) as $subCatid){ 
                    $_category = Mage::getModel('catalog/category')->load($subCatid);
                if($_category->getIsActive()) { ?>


                    <div class="categorypageslide w-slide" style="transform: translateX(0px); opacity: 1;">
                        <div class="categorypageslidepic"></div>
                        <div class="categorypageslidetitle">
                            <a href="<?php echo $_category->getURL(); ?>"><h4 class="categorypageslidetitletext"><?php echo $_category->getName(); ?></h4></a>
                        </div>
                    </div>

                <?php }} ?>
                </div>


                    <div class="w-slider-arrow-left">
                        <div class="prodslideicon w-icon-slider-left"></div>
                    </div>
                    <div class="w-slider-arrow-right">
                        <div class="prodslideicon w-icon-slider-right"></div>
                    </div>
                </div>
            </div>
        </div>
        <div class="cartcheckoutwrap w-clearfix">
            <div class="checkoutwrap">
                <h4 class="checktext">Checkout</h4>
            </div>
            <div class="cartwrap">
                <h1 class="carttext">0<span class="fa checkout"></span></h1>
            </div>
        </div>
    </div>
</body>

</html>