<!DOCTYPE html>
<!-- This site was created in Webflow. http://www.webflow.com-->
<!-- Last Published: Thu Sep 29 2016 20:09:01 GMT+0000 (UTC) -->
<html data-wf-domain="sawbones-product-homepage.webflow.io" data-wf-page="57b55b0ec24ee74912dfc688" data-wf-site="57994ac141136a134b02557d" data-wf-status="1">

<head>
    <?php echo $this->getChildHtml('head') ?>
    <link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Lato:100,100italic,300,300italic,400,400italic,700,700italic,900,900italic">
    <style type="text/css">
        html {
            -webkit-font-smoothing: antialiased;
            -moz-osx-font-smoothing: grayscale;
            text-shadow: 1px 1px 1px rgba(0,0,0,.004);
        }
    </style>
</head>
<body class="body">
    <?php echo $this->getChildHtml('header') ?>
    <div class="section1">
        <div class="top-slider w-slider" data-animation="slide" data-duration="500" data-infinite="1">
            <?php echo $this->getChildHtml('content') ?>
        </div>
        <div class="section-row w-row">
            <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('News_1')->toHtml();  ?>
            <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('Case_Studies_1')->toHtml();  ?>
        </div>
    </div>
    <div class="section3">
        <div class="section-row w-row">
            <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('Video_How_To_1')->toHtml();  ?>
            <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('Video_Overview_1')->toHtml();  ?>
            
        </div>
    </div>
</body>

</html>