<!DOCTYPE html>
<html lang="<?php echo $this->getLang(); ?>" id="top" class="no-js">
<head>
<?php echo $this->getChildHtml('head') ?>
<link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Lato:100,100italic,300,300italic,400,400italic,700,700italic,900,900italic">
<style type="text/css">
    html {
        -webkit-font-smoothing: antialiased;
        -moz-osx-font-smoothing: grayscale;
        text-shadow: 1px 1px 1px rgba(0,0,0,.004);
    }
</style>
</head>
<body class="body">
        <?php echo $this->getChildHtml('header') ?>
        <div class="section1">
<?php echo $this->getChildHtml('breadcrumbs2') ?>

                <?php echo $this->getChildHtml('global_messages') ?>
                <?php echo $this->getChildHtml('content') ?>



        </div>
</body>
</html>

