
<?php if($crumbs && is_array($crumbs)): ?>
<div class="breadcrumbs">
        <?php foreach($crumbs as $_crumbName=>$_crumbInfo): ?>
            <span class="breadnotcurrentlisting">
            <?php if($_crumbInfo['link']): ?>
                <?php echo $this->escapeHtml($_crumbInfo['label']) ?>
                <a href="<?php echo $_crumbInfo['link'] ?>" title="<?php echo $this->escapeHtml($_crumbInfo['title']) ?>"></a>
            <?php elseif($_crumbInfo['last']): ?>
                <strong><?php echo $this->escapeHtml($_crumbInfo['label']) ?></strong>
            <?php else: ?>
                <?php echo $this->escapeHtml($_crumbInfo['label']) ?>
            <?php endif; ?>
            <?php if(!$_crumbInfo['last']): ?>
                <span>/ </span>
            <?php endif; ?>
            </span>
        <?php endforeach; ?>
</div>
<?php endif; ?>
